version: 0.2

phases:
  install:
    commands:
      - echo "Debug: Current directory"
      - pwd
      - echo "Listing files..."
      - ls -la $CODEBUILD_SRC_DIR

  pre_build:
    commands:
      - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USER" --password-stdin

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - docker build -t hadinofal/coworking-space:latest .
