version: 0.2

phases:
  install:
    commands:
      - echo "Debug: Current directory"  # Ensure hyphen + space
      - pwd
      - echo "Listing files..."
      - ls -la

  pre_build:
    commands:
      - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USER" --password-stdin

  build:
    commands:
      - docker build -t hadinofal/coworking-space:latest .

  post_build:
    commands:
      - docker push hadinofal/coworking-space:latest
