# buildspec.yml
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USER" --password-stdin

  build:
    commands:
      - echo "Building Docker image from root..."
      - docker build -t hadinofal/coworking-space:latest .

  post_build:
    commands:
      - echo "Pushing to Docker Hub..."
      - docker push hadinofal/coworking-space:latest

artifacts:
  files:
    - '**/*'
