# buildspec.yml
version: 0.2

phases:
  install:
    commands:
      - echo "Debug: Current directory"
      - pwd
      - echo "Listing files..."
      - ls -la
      - cd /codebuild/output/src2039049931/src/github.com/abdelhadi-nofal/cd12355-microservices-aws-kubernetes-project-starter
      - ls -la  # Confirm Dockerfile exists

  pre_build:
    commands:
      - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USER" --password-stdin

  build:
    commands:
      - docker build -t hadinofal/coworking-space:latest .

  post_build:
    commands:
      - docker push hadinofal/coworking-space:latest
