apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  storageClassName: gp2  # AWS EBS storage class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
