# deployment/coworking.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: coworking
  template:
    metadata:
      labels:
        service: coworking
    spec:
      containers:
        - name: coworking
          image: hadinofal/coworking-space:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5153
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5153
          readinessProbe:
            httpGet:
              path: /api/health
              port: 5153
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
